services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq-gpu_nexus
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    #image: mjanith/SR-frontend
    ports:
      - "80:80"
    container_name: frontend
    depends_on:
      rabbitmq:
        condition: service_healthy

  authentication-service:
    # image: mjanith/SR-authservice:${AUTH_TAG} # Docker Hub repo image
    ports:
      - "8082:8082"
    env_file:
      - envFiles/auth.env
    container_name: authservice
    depends_on:
      rabbitmq:
        condition: service_healthy

  api-gateway:
    # image: mjanith/SR-apigateway:${API_TAG} # Docker Hub repo image
    ports:
      - "8081:8081"
    env_file:
      - envFiles/apiGateway.env
    container_name: api-gateway
    depends_on:
      rabbitmq:
        condition: service_healthy

  sorting-service:
    # image: mjanith/SR-sorting-service:${SORT_TAG} # Docker Hub repo image
    ports:
      - "8083:8083"
    env_file:
      - envFiles/sorting.env
    container_name: sorting
    depends_on:
      rabbitmq:
        condition: service_healthy
